### ISSUE TITLE
Error reading meshtal file

### ISSUE THREAD

**Issue by raulfluis** [Radiation-Transport/mesh2vtk#2]
Dear developers,

When reading meshtal files created with D1SUNED, I am getting the following error:

 "enter action :open
 enter Meshtally file name:meshtam

 Input files :
 - meshtam
Traceback (most recent call last):
  File "C:\Users\Raul\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Raul\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Raul\Anaconda3\lib\site-packages\mesh2vtk.py", line 575, in <module>
    meshtally.append(Meshtal(meshfiles[-1],filetype))
  File "C:\Users\Raul\Anaconda3\lib\site-packages\meshtal_mod.py", line 74, in __init__
    self.__scanMCNP__()
  File "C:\Users\Raul\Anaconda3\lib\site-packages\meshtal_mod.py", line 102, in __scanMCNP__
    t.__readMeshDim__(self.f)
  File "C:\Users\Raul\Anaconda3\lib\site-packages\meshtal_mod.py", line 304, in __readMeshDim__
    binlist=splitn(line[i+1:],binlen)[:-1]
  File "C:\Users\Raul\Anaconda3\lib\site-packages\meshtal_mod.py", line 57, in splitn
    return [string[i:i+n].strip() for i in xrange(0,len(string),n)]
NameError: name 'xrange' is not defined"

I am using conda 4.8.5 with Python 3.7.4 and numpy 1.16.5. Unfortunately, I could not attach the meshtal file I am trying to read, due to size limitations. 

Best regards,
Raul Luís

**Comment by Radiation-Transport** [comment]
Issue resolved in commit of 19-11-2021.

Python syntax migrated to 3.X.
